#define MIDI_Acoustic_Grand_Piano	0
#define MIDI_Bright_Acoustic_Piano	1
#define MIDI_Electric_Grand_Piano	2
#define MIDI_Honky_tonk_Piano		3
#define MIDI_Electric_Piano_1		4
#define MIDI_Electric_Piano_2		5
#define MIDI_Harpsichord			6
#define MIDI_Clavi					7
#define MIDI_Celesta				8
#define MIDI_Glockenspiel			9
#define MIDI_Music_Box				10
#define MIDI_Vibraphone				11
#define MIDI_Marimba				12
#define MIDI_Xylophone				13
#define MIDI_Tubular_Bells			14
#define MIDI_Dulcimer				15
#define MIDI_Drawbar_Organ			16
#define MIDI_Percussive_Organ		17
#define MIDI_Rock_Organ				18
#define MIDI_Church_Organ			19
#define MIDI_Reed_Organ				20
#define MIDI_Accordion				21
#define MIDI_Harmonica				22
#define MIDI_Tango_Accordion		23
#define MIDI_Acoustic_Guitar_nylon	24
#define MIDI_Acoustic_Guitar_steel	25
#define MIDI_Electric_Guitar_jazz	26
#define MIDI_Electric_Guitar_clean	27
#define MIDI_Electric_Guitar_muted	28
#define MIDI_Overdriven_Guitar		29
#define MIDI_Distortion_Guitar		30
#define MIDI_Guitar_harmonics		31
#define MIDI_Acoustic_Bass			32
#define MIDI_Electric_Bass_finger	33
#define MIDI_Electric_Bass_pick		34
#define MIDI_Fretless_Bass			35
#define MIDI_Slap_Bass_1			36
#define MIDI_Slap_Bass_2			37
#define MIDI_Synth_Bass_1			38
#define MIDI_Synth_Bass_2			39
#define MIDI_Violin					40
#define MIDI_Viola					41
#define MIDI_Cello					42
#define MIDI_Contrabass				43
#define MIDI_Tremolo_Strings		44
#define MIDI_Pizzicato_Strings		45
#define MIDI_Orchestral_Harp		46
#define MIDI_Timpani				47
#define MIDI_String_Ensemble_1		48
#define MIDI_String_Ensemble_2		49
#define MIDI_Synth_Strings_1		50
#define MIDI_Synth_Strings_2		51
#define MIDI_Choir_Aahs				52
#define MIDI_Voice_Oohs				53
#define MIDI_Synth_Voice			54
#define MIDI_Orchestra_Hit			55
#define MIDI_Trumpet				56
#define MIDI_Trombone				57
#define MIDI_Tuba					58
#define MIDI_Muted_Trumpet			59
#define MIDI_French_Horn			60
#define MIDI_Brass_Section			61
#define MIDI_SynthBrass_1			62
#define MIDI_SynthBrass_2			63
#define MIDI_Soprano_Sax			64
#define MIDI_Alto_Sax				65
#define MIDI_Tenor_Sax				66
#define MIDI_Baritone_Sax			67
#define MIDI_Oboe					68
#define MIDI_English_Horn			69
#define MIDI_Bassoon				70
#define MIDI_Clarinet				71
#define MIDI_Piccolo				72
#define MIDI_Flute					73
#define MIDI_Recorder				74
#define MIDI_Pan_Flute				75
#define MIDI_Blown_Bottle			76
#define MIDI_Shakuhachi				77
#define MIDI_Whistle				78
#define MIDI_Ocarina				79
#define MIDI_Lead_1_square			80
#define MIDI_Lead_2_sawtooth		81
#define MIDI_Lead_3_calliope		82
#define MIDI_Lead_4_chiff			83
#define MIDI_Lead_5_charang			84
#define MIDI_Lead_6_voice			85
#define MIDI_Lead_7_fifths			86
#define MIDI_Lead_8_bass_lead		87
#define MIDI_Pad_1_new_age			88
#define MIDI_Pad_2_warm				89
#define MIDI_Pad_4_choir			90
#define MIDI_Pad_5_bowed			91
#define MIDI_Pad_6_metallic			92
#define MIDI_Pad_7_halo				93
#define MIDI_Pad_8_sweep			94
#define MIDI_FX_1_rain				95
#define MIDI_FX_2_soundtrack		96
#define MIDI_FX_3_crystal			97
#define MIDI_FX_4_atmosphere		98
#define MIDI_FX_5_brightness		99
#define MIDI_FX_6_goblins			100
#define MIDI_FX_7_echoes			101
#define MIDI_FX_8_sci_fi			102
#define MIDI_Sitar					103
#define MIDI_Banjo					104
#define MIDI_Shamisen				105
#define MIDI_Koto					106
#define MIDI_Kalimba				107
#define MIDI_Bag_pipe				108
#define MIDI_Fiddle					109
#define MIDI_Shanai					110
#define MIDI_Tinkle_Bell			111
#define MIDI_Agogo					112
#define MIDI_Steel_Drums			113
#define MIDI_Woodblock				114
#define MIDI_Taiko_Drum				115
#define MIDI_Melodic_Tom			116
#define MIDI_Synth_Drum				117
#define MIDI_Reverse_Cymbal			118
#define MIDI_Guitar_Fret_Noise		119
#define MIDI_Breath_Noise			120
#define MIDI_Seashore				121
#define MIDI_Bird_Tweet				122
#define MIDI_Telephone_Ring			123
#define MIDI_Helicopter				124
#define MIDI_Applause				125
#define MIDI_Gunshot				126